### ISSUE TITLE
扫描出的条目不全

### ISSUE THREAD

**Issue by xgeeek** [HayDar-Android/FileScanner#2]
根路径：Environment.getExternalStorageDirectory().getPath()
同一台手机；

我用系统File类过滤条件扫描到的（.bin）文件是91个
代码如下：
file.listFiles(new FileFilter() {
            @Override
            public boolean accept(File pathname) {
                /*true 为收集文件*/
                if (pathname.isDirectory()) {
                    return true;
                } else {
                    return pathname.getName().endsWith(".bin");
                }
            }
        });

用你的代码全盘扫描出来的只有60个，多次扫描结果都一样。
想问楼主什么原因？

**Comment by HayDar-Android** [comment]
@xgeeek 具体我也不清楚，你可以扫描出来，坐下对比，主要是哪个文件夹下扫描不到，按理说不应该的
